[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--durations=3"

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
fail_under = 80

[tool.isort]
profile = "black"
force_single_line = true

[tool.mypy]
ignore_missing_imports = true
namespace_packages = true
